### ISSUE TITLE
nosetests modules not deployed

### ISSUE THREAD

**Issue by machinekoder** [machinekit/machinekit#1139]
It looks like the nosetests Python modules are not deployed with the `machinekit-dev` package. If not deployed with `machinekit-dev` there should be a `machinekit-test` package.

```
======================================================================
ERROR: Failure: ImportError (No module named nosetests.realtime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/vagrant/pmcs-sim/python/tst_pmcs_tool_info_integration.py", line 4, in <module>
    from machinekit.nosetests.realtime import setup_module, teardown_module
ImportError: No module named nosetests.realtime
```

**Comment by ArcEye** [comment]
Didn't realise they were not there already, but then I don't use python.

I have fixed it for you, I put them in the main machinekit package, the -dev package is a bit of an anachronism and the extra code is barely 1 page long.

Perhaps you could look at #1136 so we can kick that into the long grass before I make any other changes.
